version: '3.3'
services:
  mongodb:
    image: mongo:3.6.3-jessie
    container_name: "blog_mongodb"
    environment:
      - MONGODB_DATA_DIR=/data/database_mongodb
      - MONGODB_LOG_DIR=/log/log_mongodb
      - MONGODB_USER="mouse"
      - MONGODB_PASS="123qwe"
    volumes:
      - ./data_mongodb:/data/database_mongodb
      - ./log/log_mongodb:/log/log_mongodb
    # command: mongod --smallfiles --logpath=/log/log_mongodb
    ports:
      - 27017:27017
  app:
    image: node:8.9.4
    container_name: "blog_app"
    environment:
      - "TZ=Asia/Bangkok"
    volumes:
      - ./:/var/www/html/app
    links:
      - mongodb
    depends_on:
      - mongodb
    working_dir: /var/www/html/app
    command: >
      bash -c "npm install && npm run watch"
    # ports:
    #   - 3000:3000
  nginx:
    image: nginx:1.13.8
    container_name: "blog_nginx"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl:/var/ssl
    links:
      - app
    depends_on:
      - app
    restart: always
    ports:
      - 80:80
      - 443:443